Rails.application.routes.draw do
  get "templates/show"
  root "sessions#new"
  get "login", to: "sessions#new"
  get "avaliacao", to: "avaliacoes#show"
  get "resultados", to: "resultados#show"
  get "templates", to: "templates#show"
  get "enviar_forms", to: "enviar_forms#show"
  get "mudar_senha", to: "mudar_senha#show"
  get "/forms/:id", to: "forms#show"
  post "usuarios/activate", to: "usuarios#activate"
  post "usuarios/login", to: "usuarios#login"
  delete "usuarios/logout", to: "usuarios#logout"
  post "usuarios/change_password", to: "usuarios#change_password"
end
